# petra - maisteri7kiva
insert into User(email, username, password) values("TODO@TODO.fi", "petrTODOa", "$2a$12$FtON0SKvY56iIxiHZb916.2dd");

alter table Category CHANGE COLUMN created created TIMESTAMP DEFAULT CURRENT_TIMESTAMP ;
alter table Chat CHANGE COLUMN created created TIMESTAMP DEFAULT CURRENT_TIMESTAMP ;
alter table User CHANGE COLUMN created created TIMESTAMP DEFAULT CURRENT_TIMESTAMP ;

insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_ruisrock", "Ruisrock", 1, "Turku", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-07-07', '2017-07-09', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_ilosaarirock", "Ilosaarirock", 2, "Joensuu", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-07-14', '2017-07-16', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_slush", "Slush", 3, "Helsinki", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-08-29', '2017-08-30', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_nordicbusinessforum", "Nordic Business Forum", 4, "Helsinki", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-09-15', '2017-09-16', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_tubecon", "TubeCon", 5, "Helsinki", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-09-15', '2017-09-16', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_studiamessut", "Studia-Messut", 6, "Helsinki", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-10-02', '2017-10-03', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_pohjoinenteollisuus", "Pohjoinen Teollisuus", 7, "Oulu", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-11-05', '2017-11-07', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_helsinkicoffeefestival", "Helsinki Coffee festival", 8, "Helsinki", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-03-21', '2017-03-23', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_siivouspaiva", "Siivouspäivä", 9, "Helsinki", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-05-27', '2017-05-27', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_maailmakylassa", "Maailma kylässä", 10, "Helsinki", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-05-27', '2017-05-28', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_raumanmerenjuhannus", "RMJ", 11, "Rauma", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-06-22', '2017-06-24', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_himosjuhannus", "Himos Juhannus", 12, "Himos", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-06-22', '2017-06-24', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_tahkojuhannus", "Tahko Juhannus", 13, "Tahko", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-06-23', '2017-06-24', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_provinssi", "Provinssi", 14, "Seinäjoki", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-06-29', '2017-07-01', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_porijazz", "Pori Jazz", 15, "Pori", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-07-08', '2017-07-16', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_kotkanmeripaivat", "Kotkan meripäivät", 16, "Kotka", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-07-12', '2017-07-16', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_suomipopfestivaali", "SuomiPOP festivaali", 17, "Jyväskylä", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-07-13', '2017-07-15', "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, place, validFrom, validTo,startTime,endTime, timezone) values("EVENT","event_flowfestival", "Flow festival", 18, "Helsinki", now(), DATE_ADD(NOW(), INTERVAL 1 YEAR), '2017-08-11', '2017-08-13', "Europe/Helsinki");


insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_random_icon", "Random", 1,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_politics_icon", "Politics", 2,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_news_icon", "News", 3,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_religion_icon", "Religion", 4,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_fitness_icon", "Health & Fitness", 5,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_videogame_icon", "Video games", 6,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_sports_icon", "Sports", 7,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_science_icon", "Science", 8,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_music_icon", "Music", 9,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_philosophy_icon", "Philosophy", 10,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_workandbusiness_icon", "Work & Business", 11,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_programming_icon", "Programming", 12,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_fashion_icon", "Fashion", 13,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_anime_icon", "Anime", 14,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_travel_icon", "Travel", 15,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_cooking_icon", "Food & Cooking", 16,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
insert into Category(type, iconName, name, ordinal, validFrom, validTo,startTime,endTime, timezone) values("GENERAL","general_chat_nsfw_icon", "Nsfw", 17,now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), now(), DATE_ADD(NOW(), INTERVAL 20 YEAR), "Europe/Helsinki");
